language: go

go:
 - 1.7

before_install:
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls

script:
 - make melkor
 - overalls -project=github.com/alde/melkor -covermode=count
 - goveralls -coverprofile=overalls.coverprofile -service travis-ci
